### ISSUE TITLE
fund-link error

### ISSUE THREAD

**Issue by pappas999** [appliedblockchain/chainlink-consumer#4]
Getting an error after following instructions and adding the 'fund-link' plugin to a hardhat repo

**Steps to reproduce:**

- Install plugin and add entry to hardhat.config.js as per the fund link README instructions
`npm install @appliedblockchain/chainlink-plugins-fund-link @nomiclabs/hardhat-ethers --save`
`require("@appliedblockchain/chainlink-plugins-fund-link");`

- Change hardhat.config.js to kovan as default network, and run npx hardhat deploy

**Output**
```
Error: Cannot find module '@appliedblockchain/chainlink-contracts/abi/LinkTokenInterface.json'
Require stack:
- /Users/pappas99/GitHub/mfhh2/node_modules/@appliedblockchain/chainlink-plugins-fund-link/dist/src/fund-link.js
- /Users/pappas99/GitHub/mfhh2/node_modules/@appliedblockchain/chainlink-plugins-fund-link/dist/src/index.js
- /Users/pappas99/GitHub/mfhh2/hardhat.config.js
- /Users/pappas99/GitHub/mfhh2/node_modules/hardhat/internal/core/config/config-loading.js
- /Users/pappas99/GitHub/mfhh2/node_modules/hardhat/internal/cli/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/pappas99/GitHub/mfhh2/node_modules/@appliedblockchain/chainlink-plugins-fund-link/src/fund-link.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/pappas99/GitHub/mfhh2/node_modules/@appliedblockchain/chainlink-plugins-fund-link/dist/src/fund-link.js',
    '/Users/pappas99/GitHub/mfhh2/node_modules/@appliedblockchain/chainlink-plugins-fund-link/dist/src/index.js',
    '/Users/pappas99/GitHub/mfhh2/hardhat.config.js',
    '/Users/pappas99/GitHub/mfhh2/node_modules/hardhat/internal/core/config/config-loading.js',
    '/Users/pappas99/GitHub/mfhh2/node_modules/hardhat/internal/cli/cli.js'
  ]
}
```

**Comment by fabioDMFerreira** [comment]
The plugin wasn't using the `@appliedblockchain/chainlink-contracts` as a dependency. I've just published a new version of the plugin with the fix.
